config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/web'

  get 'pages/portal'

  get 'pages/about'

  get 'pages/comp'

  get 'pages/contact'

  get 'pages/design'

  get 'pages/eversion'

  get 'pages/home'

  get 'pages/litho'

  get 'pages/products_services'

  get 'pages/shipping'

  get 'pages/RWPedia'

  root 'pages#home'

  resources :words

  get "admin" => 'admin/dashboard#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ActiveRecord::Base

	scope :by_letter,
        lambda { |letter| {
            :conditions => ["words.word LIKE ?", "#{letter}%"]
        }}
        
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def products_services
  end

  def RWPedia
    @words, @alphaParams = Word.all.alpha_paginate(params[:letter], {:default_field => "all", :js => false, :bootstrap3 => true, :pagination_class => "pagination-centered"}){|word| word.word}
  end

  def about
  end

  def contact
  end

  def portal
  end
    
  def comp
  end
    
  def design
  end

  def eversion
  end
    
  def litho
  end
    
  def shipping
  end
    
  def web
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

# for alphabetical paginate:
  def index
    @words, @alphaParams = Word.all.alpha_paginate(params[:letter], {:default_field => "all", :js => false, :bootstrap3 => true, :pagination_class => "pagination-centered"}){|word| word.word}
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/words_helper.rb
module WordsHelper

end

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/layouts/_footer.html.erb
    <div class="container-fluid max nav-cont-foot">
        <span>© 2015 Ricter Web Printing Ltd.</span>
    </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-trans">
<!-- <nav class="navbar navbar-inverse navbar-fixed-top"> Replace above line with this to fix the nav to the top-->
  <div class="container-fluid max">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img> <%= link_to image_tag('RWPlogow.svg'), pages_home_path, class: "navbar-brand"%> </img>
    </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Products and Services 
                  <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Web Printing", pages_web_path%></li>
                <li><%= link_to "Lithographic Printing", pages_litho_path%></li>
                <li><%= link_to "Digital Printing and Sign Printing", "http://www.peekimaging.ca/", :target => "_blank" %></li>
                <li class="divider"></li>
                <li><%= link_to "Prepress", pages_comp_path%></li>
                <li><%= link_to "eVersion", pages_eversion_path%></li>
                <li><%= link_to "Graphic and Publication Design", pages_design_path%></li>
                <li class="divider"></li>
                <li><%= link_to "Shipping with CST", "http://www.cstlogistics.com/", :target => "_blank" %></li>
              </ul>
            </li>  
            <li><%= link_to "About Us", pages_about_path %></li>
            <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "RWPedia", pages_RWPedia_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RicterSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="gradient-primary">
        <div class="push-container">
            <%= render "layouts/header" %>
            <br>
            	<%= yield %>
            <div class="footer-push"></div>
        </div>
        <%= render "layouts/footer" %>
</body>
</html>

app/views/pages/RWPedia.html.erb
<%= render "words/index" %>

app/views/pages/about.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-6" >
            <h1>Our Company</h1>
            <p>
                        Ricter Web printing is primarily a coldset web printer, however Ricter Web is far more than just web printing.
We have fantastic design talent in our design department, a five-colour sheetfed press, a well-equipped bindery department and a dedicated shipping company, <a href="http://www.cstlogistics.com/" target="_blank">CST Logistics</a>. Beyond our proverbial "four walls", we have numerous service providers that we partner with to bring you an even wider gamut of professional services.
                </p><p>
Back in 1975, Ricter Web Printing was founded as a local newspaper with in-house printing. As the years rolled on, the printing grew and eventually replaced the publishing. Today publishers can be assured that, with our roots firmly planted in their end of the business, we understand their needs, concerns and ideals.
                </p><p>
Ever since the beginning, Ricter Web has striven to be the best, to improve and stay ahead of the rest of the crowd; today our passion for excellence continues.
                </p>
        </div> 
        <div class="col-md-6" >
            <iframe width="560" height="315" src="https://www.youtube.com/embed/z9XmSlH_cjg" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>

app/views/pages/comp.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-4" >
            <img <%= link_to image_tag('LightTable300px.jpg'), class: "img-responsive"%>
        </div>
        <div class="col-md-8" >
            <h1>Prepress</h1>
            <p>
                        These are the heroes that take your files process them and get them on press, working with some of the shortest turnaround times and highest standards in the industry.
</p><p>
Our prepress crew will work with you to make sure that your files are the best that they can be. With staff working from 8am to 2am, there is sure to be someone here to give you professional service and advice right when you need it.
</p><p>
We have proofing devices finger printed and matched to both our web presses and our sheetfed litho press.To supplement this we also offer soft proofing over the internet to help you meet the tight deadlines that we all have to work with, and to save you a few miles in your car.
</p><p>
Talk to a sales person to today for all your printing needs.
                </p>
        </div>    

    </div>
</div>

app/views/pages/contact.html.erb
<div class="page">

    <!-- new! -->
    <input type="radio" id="nav-expand" name="nav" class="invis" />
    <nav class="nav-side">
      <label for="nav-collapse" class="close">
        &times;
      </label>
      <!-- new! -->
      <label for="nav-expand" class="btn-label">
        <span class="top"></span><span class="middle"></span><span class="bottom"></span><span class="label">Staff</span>
      </label>

      <ol class="menu-list contact-menu">
        
          <div id="MainMenu">
  <div class="list-group panel">
    <a href="#admin" class="list-group-item" data-toggle="collapse" data-parent="#MainMenu">Administration</a>
    <div class="collapse" id="admin">
      <div class="list-group-item">
        <li data-target="#carousel-example-generic" data-slide-to="7" class="active bs-docs-sidebar nav">Rick StAmand</li>
        <li data-target="#carousel-example-generic" data-slide-to="6" class="bs-docs-sidebar nav">Terry StAmand</li>
        <li data-target="#carousel-example-generic" data-slide-to="0">Jim Turnbull</li>
        <li data-target="#carousel-example-generic" data-slide-to="5">Jonathan Bowen</li>
      </div>
    </div>
    <a href="#production" class="list-group-item" data-toggle="collapse" data-parent="#MainMenu">Production</a>
    <div class="collapse" id="production">
      <div class="list-group-item">
        <li data-target="#carousel-example-generic" data-slide-to="1" class="active bs-docs-sidebar nav">Dave Hill</li>
        <li data-target="#carousel-example-generic" data-slide-to="2" class="bs-docs-sidebar nav">Donna Bradley</li>
        <li data-target="#carousel-example-generic" data-slide-to="3">Gail Casler</li>
        <li data-target="#carousel-example-generic" data-slide-to="4">Jim Barney</li>
      </div>
    </div>
    <a href="#comp" class="list-group-item" data-toggle="collapse" data-parent="#MainMenu">Composing</a>
    <div class="collapse" id="comp">
      <div class="list-group-item">
        <li data-target="#carousel-example-generic" data-slide-to="8" class="active bs-docs-sidebar nav">Design</li>
        <li data-target="#carousel-example-generic" data-slide-to="9" class="bs-docs-sidebar nav">Prepress</li>
        <li data-target="#carousel-example-generic" data-slide-to="10">Velibor Stankovic</li>
      </div>
    </div>
  </div>
</div>
      </ol>
        
    </nav>
    

<div class="back-section1" id="contact-content">
    <div class="contact-car-max">
    <input type="radio" id="nav-collapse" name="nav" checked="checked" class="invis" />
        
            <main class="main-base" role="main">
                

                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="false">

                          <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img <%= link_to image_tag('JimTurnbull.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('DaveHill.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('DonnaBradley.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('GailCasler.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('JimBarney.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('JonathanBowen.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('TerryStAmand.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('RickStAmand.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('DesignTeam.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('prepress.jpg'), class: "img-responsive"%>
                            </div>
                            <div class="item">
                                <img <%= link_to image_tag('VelStankovic.jpg'), class: "img-responsive"%>
                            </div>
                        </div>
                    </div>
                        <label for="nav-collapse"></label>
                </div>
            </div>
        </main>
    </div>
</div>
<br>
<br>

app/views/pages/design.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-4" >
            <img <%= link_to image_tag('Design-pic-for-web-small.jpg'), class: "img-responsive"%>
        </div>
        <div class="col-md-8" >
            <h1>Graphic &amp; Publication Design</h1>
            <p>
                        Why go to an advertising agency to design your work when it can all be done in house here by our outstanding talent.
    All of our designers are experienced professionals and can make you a fantastic piece for a fraction of what it would cost you at a commercial agency.
    Ask your account representative for samples, or better yet give us a try, you will find our designers creative, efficient and courteous.
                </p>
        </div>    

    </div>
</div>

app/views/pages/eversion.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-5" >
            <h1>Why E-Publishing?</h1>
            <p>
                        Consumers are looking for more ways to read, interact and sort through information. Our solution is a cost –effective product that will allow you to further build and strengthen consumer relationships.
The reality is that the Internet is here to stay. Print buyers want to leverage printed materials to ensure that their customers have the ability to view the content whatever the medium.
Click <a href="http://www.flippubs.com/publication?i=81389" target="_blank">Here</a> to view an example
                </p>
        </div> 
        <div class="col-md-7" >
            <iframe width="560" height="315" src="http://www.youtube.com/embed/U-D3cvaJEvE" frameborder="0" allowfullscreen></iframe>

        </div>
    </div>
</div>

app/views/pages/home.html.erb
<!-- this is the slide show carousel -->
<div class="back-section1">
    <div class="car-max">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="http://www.ricterweb.com/randim/images/2.jpg">
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <img src="http://www.ricterweb.com/randim/images/4.jpg">
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <img src="http://www.ricterweb.com/randim/images/5.jpg">
                <div class="carousel-caption">
                </div>
            </div>
              <div class="item">
                <img src="http://www.ricterweb.com/randim/images/3.jpg">
                <div class="carousel-caption">
                </div>
            </div>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div> 
</div>
<div class="container-fluid max">
    <!-- this is the body text -->
    <div class="col-md-12" >
        <h1>Ricter Web Printing</h1>
        <div class="col">
                <p>
                    Ricter Web Printing is a family owned and operated business established in 1975.
                    We are proud of our "All Star Cast" of professionals who are always eager to provide the customer with a 5-star performance.
                    Epic quality and outstanding service are the primary objectives involved in meeting the printing requirements of a fast-paced high-tech marketplace!
                    Our clients are treated with the respect and integrity they deserve. From start to finish, customer satisfaction is paramount.
                </p> 

                <!-- this is to test CMSimple -->
                <h1 id='page_title' class="page-heading" data-mercury='full'>
                  <%= render_region :page_title do %>
                    Placeholder
                  <% end %>
                </h1> 
        </div>
    </div>

    <!-- this is the two items at the bottom below the about text. -->
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-1 col-md-3 col-md-offset-2">
          <div class="well well-lg well-rwp">
                <iframe marginheight="0" marginwidth="0" name="wxButtonFrame" id="wxButtonFrame" height="168" src="http://btn.weather.ca/weatherbuttons/template7.php?placeCode=CAON0081&category0=Cities&placeCode1=CAON0383&category1=&placeCode2=CAON0109&category2=&placeCode3=CAON0289&category3=Cities&placeCode4=CAON0696&category4=&containerWidth=180&btnNo=&backgroundColor=blue&multipleCity=1&citySearch=0&celsiusF=C" align="top" frameborder="0" width="180" scrolling="no" allowTransparency="true"></iframe>
          </div>
        </div>
        <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-2">
          <div class="well well-lg well-rwp">
                <span class="glyphicon glyphicon-briefcase glyph-large" aria-hidden="true"></span><br>
                Start a Career with RWP!
          </div>
        </div>
    </div>
</div>

app/views/pages/litho.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-4" >
            <img <%= link_to image_tag('litho02.jpg'), class: "img-responsive"%>
        </div>
        <div class="col-md-8" >
            <h1>Lithographic Printing</h1>
            <p>
                        Ricter Web printing is primarily a coldset web printer, however Ricter Web is far more than just web printing.
We have fantastic design talent in our design department, a five colour sheetfed press, a well equipped bindery department and a dedicated shipping company, CST Logistics.
Beyond our proverbial four walls we have numerous service providers that we cooperate with to bring to you a an even wider gamut of professional services.
                </p>
        </div>    

    </div>
</div>

app/views/pages/portal.html.erb
<h1>Pages#portal</h1>
<p>Find me in app/views/pages/portal.html.erb</p>

app/views/pages/products_services.html.erb
s
<div class="container-fluid max">
    

<!-- this is the body text -->
    <div class="col-md-12" >
        <h1>Ricter Web Printing</h1>
        <div class="col">
                <p>
                    Ricter Web Printing is a family owned and operated business established in 1975.
                    We are proud of our "All Star Cast" of professionals who are always eager to provide the customer with a 5-star performance.
                    Epic quality and outstanding service are the primary objectives involved in meeting the printing requirements of a fast-paced high-tech marketplace!
                    Our clients are treated with the respect and integrity they deserve. From start to finish, customer satisfaction is paramount.
                </p>  
        </div>
    </div>

    <!-- this is the two items at the bottom below the about text. -->
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2 col-sm-3 col-sm-offset-2">
          <div class="well well-lg well-rwp">
                <iframe marginheight="0" marginwidth="0" name="wxButtonFrame" id="wxButtonFrame" height="168" src="http://btn.weather.ca/weatherbuttons/template7.php?placeCode=CAON0081&category0=Cities&placeCode1=CAON0383&category1=&placeCode2=CAON0109&category2=&placeCode3=CAON0289&category3=Cities&placeCode4=CAON0696&category4=&containerWidth=180&btnNo=&backgroundColor=blue&multipleCity=1&citySearch=0&celsiusF=C" align="top" frameborder="0" width="180" scrolling="no" allowTransparency="true"></iframe>
          </div>
        </div>
        <div class="col-xs-8 col-xs-offset-2 col-sm-3 col-sm-offset-2">
          <div class="well well-lg well-rwp">
                <span class="glyphicon glyphicon-briefcase glyph-large" aria-hidden="true"></span><br>
                Start a Career with RWP!
          </div>
        </div>
    </div>
</div>

app/views/pages/shipping.html.erb
<h1>Pages#shipping</h1>
<p>Find me in app/views/pages/shipping.html.erb</p>

app/views/pages/web.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
        <div class="col-md-4" >
            <img <%= link_to image_tag('web002-72.jpg'), class: "img-responsive"%>
        </div>
        <div class="col-md-8" >
            <h1>Coldset Web Printing</h1>
            <p>
                        Coldset web printing used to mean lots of poor-quality product — fast. At Ricter Web, coldset web is redefined to the point that it is not recognizable. Our quality is outstanding, with resolution that used to only be possible on tightly controlled sheetfed presses.
Our web presses are outfitted with numerous quality-enhancing options to control the print process more closely. This is backed up by a state-of-the-art prepress department. This ground-breaking technology continually adjusts all parameters to meet our high standards prior to going to plate.
Our plates are imaged with high-resolution thermal laser using stochastic dots, which allow phenomenal clarity and detail rendition, second to nothing in the industry.
Our web presses are configured to offer tremendous scalability suitable for everything from a four-page flyer, to thick multi-page sections. We have a theoretical maximum of 5 rolls of paper through 5 presses simultaneously, to give up to 80 full-colour pony (demi-tab, slightly smaller than office letter size) pages in one section. The power is all yours at Ricter Web.
Talk to a sales person to today for all your web printing needs.
                </p>
        </div>    

    </div>
</div>

app/views/words/_index.html.erb
<div class="back-section1">
    <div class="container-fluid max vert-pad">
<nav  >
  <ul type="button" class="navbar-btn">
      <%= alphabetical_paginate @alphaParams %>
  </ul>
</nav>

<div id="pagination_table">
  <div class="col-md-2" ><strong>Word</strong></div>
  <div class="col-md-10" ><strong>Definition</strong></div>

  
    <% grouped_words = @words.group_by {|w| w.word[0].upcase } %>
  
    <% grouped_words.each do |l, w| %>
      <div class="col-md-12" ><h3><%= l %></h3></div>
      <% w.each do |i| %>
        <div class="col-md-2" ><strong><%= i.word %></strong></div>
        <div class="col-md-10" ><p><%= i.definition %></p></div>
        <div class="col-md-12" ><br></div>
      <% end %>
    <% end %>
</div>
</div>
</div>





<table class="table">
  ...
</table>

app/views/words/index-test.html.haml
%nav.navbar.navbar-inverse
  %ul{:type => "button", .btn .btn-default .navbar-btn}
    = alphabetical_paginate @alphaParams


#pagination_table
%table
  %thead
    %tr
      %th Word
      %th Definition
      %th {colspan="3"}


%tbody
  -grouped_words = @words.group_by {|w| w.word[0].upcase }
    -grouped_words.each do |l, w|
      %tr
        %td 
          %h3 = l
          -w.each do |i|
            %tr
              %td = i.word
              %td = i.definition
          end
    end


%br